### ISSUE TITLE
Logo doesn't update based on chapter

### ISSUE THREAD

**Issue by ryan-bello** [hack4impact/chapter-website-template#2]
I've noticed that the logo doesn't adjust depending on the chapter. It seems to be a static link, as you can in the code block below, which is from "\components\navbar\Logo.jsx"

```
function Logo() {
  return (
    <>
      <Link href="/">
        <a className="image-container" ariaLabel="Go to homepage">
          <img
            className="university-logo"
            height="40"
            src="https://images.ctfassets.net/dz50cburkkql/7trWXZia556Z9uftKAMCz/dc3b7d7fc1aa07ca0d752d09df6a01a5/Georgia_Tech_Yellow_Jackets_logo.svg"
            alt=""
          />
```

**Comment by Holben888** [comment]
This is related to an ongoing issue with NextJS: you can't fetch content (say, Contentful images) from the `_app.jsx` layout file 😢 [More on that issue here](https://nextjs.org/docs/advanced-features/custom-app#caveats)

This means we can't fetch the University logo for the navbar, which _needs_ to be a part of the layout file. I'll close this issue until NextJS comes out with a fix.
